In [1]:
import xarray as xr
ds = xr.open_dataset("./wind.slf", engine="selafin")

In [2]:
ds

<xarray.Dataset> Size: 12MB
Dimensions:  (time: 97, node: 10363)
Coordinates:
    x        (node) float32 41kB ...
    y        (node) float32 41kB ...
  * time     (time) datetime64[ns] 776B 2018-10-30 ... 2018-11-03
Dimensions without coordinates: node
Data variables:
    X        (time, node) float32 4MB ...
    Y        (time, node) float32 4MB ...
    P        (time, node) float32 4MB ...
Attributes:
    title:       ATHABASCA RIVER
    language:    en
    float_size:  4
    endian:      >
    params:      (1, 0, 0, 0, 0, 0, 0, 2590, 0, 1)
    ipobo:       [    1     2     3 ... 10361 10362 10363]
    ikle2:       [[8124 8122 8052]\n [7871 7790 7791]\n [3878 4035 3871]\n .....
    variables:   {'X': ('WIND ALONG X', 'M/S'), 'Y': ('WIND ALONG Y', 'M/S'),...
    date_start:  (2018, 10, 30, 0, 0, 0)

In [6]:
import numpy as np
np.shape(ds.X.values)

(97, 10363)

In [3]:
ds2 = xr.open_dataset("./atm_wind_txy.slf", engine="selafin")
ds2

<xarray.Dataset> Size: 56kB
Dimensions:  (time: 21, node: 319)
Coordinates:
    x        (node) float32 1kB ...
    y        (node) float32 1kB ...
  * time     (time) datetime64[ns] 168B 1900-01-01T00:08:20 ... 1900-01-01T00...
Dimensions without coordinates: node
Data variables:
    WINDX    (time, node) float32 27kB ...
    WINDY    (time, node) float32 27kB ...
Attributes:
    title:       SET UP OF WIND VARYING IN TIME AND SPACE
    language:    en
    float_size:  4
    endian:      >
    params:      (1, 0, 0, 0, 0, 0, 0, 0, 0, 1)
    ipobo:       [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...
    ikle2:       [[255 279 277]\n [120 121 154]\n [259 275 276]\n ...\n [  3 ...
    variables:   {'WINDX': ('WINDX', ''), 'WINDY': ('WINDY', '')}
    date_start:  (1900, 1, 1, 0, 8, 20)

In [5]:
ds.x.values

array([-77.593506, -77.57457 , -77.58149 , ..., -79.714066, -79.70323 ,
       -79.70956 ], dtype=float32)

In [6]:
ds.X.values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [7]:
ds.ikle2 

array([[8124, 8122, 8052],
       [7871, 7790, 7791],
       [3878, 4035, 3871],
       ...,
       [3333, 3532, 3332],
       [3145, 3332, 3157],
       [3334, 3147, 3148]], dtype='>i4')